### ISSUE TITLE
장고 프로젝트 생성 템플릿 오류

### ISSUE THREAD

**Issue by hansanhha** [KimSoungRyoul/django-backend-starter#1]
```
django-admin startproject --template=https://github.com/KimSoungRyoul/django-backend-starter/archive/django-backend-starter-template.zip  hello_django_project
```
README에 적어주신 링크대로 장고 프로젝트를 생성하려고 했으나 https://github.com/KimSoungRyoul/django-backend-starter/archive/django-backend-starter-template.zip 를 다운로드할 수 없고 404 Not Found 응답을 받습니다

**Comment by KimSoungRyoul** [comment]
안녕하세요 
프로젝트 간소화 작업하면서 누락된 부분이 있었습니다
한번 더 수행해볼수있을까요?

**Comment by hansanhha** [comment]
네 정상적으로 잘 됩니다 ! 
작가님 덕분에 DRF 입문을 탄탄히 할 수 있을 것 같아서 감사 인사 드립니다
템플릿과 깃허브 코드 열심히 참고할게요 😀
